version: 2

jobs:
  build:
    machine: true

    working_directory: ~/package

    steps:
      - checkout

      - run:
          name: Start build container
          command: |
            mkdir -p ~/repo
            docker run --privileged --name fb -it -d \
            -e CIRCLE_BRANCH=$CIRCLE_BRANCH \
            -e CIRCLE_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL \
            -e CIRCLE_SHA1 \
            -v ~/.ssh:/root/.ssh \
            -v ~/package:/root/package \
            -v ~/repo:/root/repo \
            knopki/cci-flatpak-builder:v0.1.0 /bin/bash

      - run:
          name: Checkout repository
          command: |
            docker exec -it fb bash -c '
              if [ $CIRCLE_BRANCH == "master" ]; then
                git config --global user.email "korolev.srg@gmail.com"
                git config --global user.name "Sergey Korolev"
                git clone $CIRCLE_REPOSITORY_URL /root/repo
                cd /root/repo
                git checkout gh-pages || git checkout --orphan gh-pages && (git rm -rf . || true)
                [[ -d /root/repo/refs ]] || ostree init --mode=archive-z2 --repo=/root/repo
                echo "gpg-verify-summary=false" >> /root/repo/config
              else
                [[ -d /root/repo/refs ]] || ostree init --mode=archive-z2 --repo=/root/repo
                [[ -d /root/repo/refs/remotes ]] || \
                  mkdir -p /root/repo/refs/remotes && touch /root/repo/refs/remotes/.gitkeep
              fi'


      - run:
          name: Add flathub repo
          command: |
            docker exec -it fb bash -c '
              flatpak --user remote-add --if-not-exists \
                flathub https://flathub.org/repo/flathub.flatpakrepo'

      - run:
          name: Build
          command: |
            docker exec -it fb bash -c '
              cd /root
              flatpak-builder --user --ccache --require-changes --repo=/root/repo \
                --subject="bat, built at `date`" \
                --install-deps-from=flathub --rebuild-on-sdk-change \
                /root/build /root/package/com.github.sharkdp.Bat.yaml'

      - run:
          name: Publish repo
          command: |
            docker exec -it fb bash -c '
            if [ $CIRCLE_BRANCH == "master" ]; then
              cd /root/repo
              flatpak build-update-repo --prune --prune-depth=20 \
                --generate-static-deltas /root/repo
              rm -rf /root/repo/.lock
              git add -A
              git commit --allow-empty \
                -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}"
              git push origin gh-pages
            fi'
