version: 2

jobs:
  build:
    machine: true

    working_directory: ~/package

    steps:
      - checkout

      - run:
          name: Start build container
          command: |
            mkdir -p ~/repo ~/.flatpak-builder ~/.local/share/flatpak
            docker run --privileged --name fb -it -d \
            -e CIRCLE_BRANCH=$CIRCLE_BRANCH \
            -e CIRCLE_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL \
            -e CIRCLE_SHA1 \
            -v ~/.ssh:/root/.ssh \
            -v ~/package:/root/package \
            -v ~/repo:/root/repo \
            -v ~/.flatpak-builder:/root/flatpak-builder-cache \
            -v ~/.local/share/flatpak:/root/.local/share/flatpak \
            knopki/cci-flatpak-builder:v0.1.0 /bin/bash

      - run:
          name: Checkout repository
          command: |
            docker exec -it fb bash -c '
              if [ $CIRCLE_BRANCH == "master" ]; then
                git config --global user.email "korolev.srg@gmail.com"
                git config --global user.name "Sergey Korolev"
                git clone $CIRCLE_REPOSITORY_URL /root/repo
                cd /root/repo
                git checkout gh-pages || git checkout --orphan gh-pages && git rm -rf
              else
                [[ -d /root/repo/refs ]] || ostree init --mode=archive-z2 --repo=/root/repo
                [[ -d /root/repo/refs/remotes ]] || \
                  mkdir -p /root/repo/refs/remotes && touch /root/repo/refs/remotes/.gitkeep
                echo "gpg-verify-summary=false" >> /root/repo/config
              fi'

      - restore_cache:
          keys:
            - v1-builder-{{ arch }}-{{ .Branch }}

      - run:
          name: Add flathub repo
          command: |
            docker exec -it fb bash -c '
              flatpak --user remote-add --if-not-exists \
                flathub https://flathub.org/repo/flathub.flatpakrepo'

      - run:
          name: Build
          command: |
            docker exec -it fb bash -c '
              cd /root
              mkdir -p /root/.flatpak-builder
              mv /root/flatpak-builder-cache/* /root/.flatpak-builder
              flatpak-builder --user --ccache --require-changes --repo=/root/repo \
                --subject="bat, built at `date`" \
                --install-deps-from=flathub --rebuild-on-sdk-change \
                /root/build /root/package/com.github.sharkdp.Bat.yaml
              mv /root/.flatpak-builder/* /root/flatpak-builder-cache'

      - save_cache:
          key: v1-builder-{{ arch }}-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.flatpak-builder
            - ~/.local/share/flatpak

      - run:
          name: Publish repo
          command: |
            docker exec -it fb bash -c '
            if [ $CIRCLE_BRANCH == "master" ]; then
              cd /root/repo
              flatpak build-update-repo --prune --prune-depth=20 \
                --generate-static-deltas /root/repo
              rm -rf /root/repo/.lock
              git add -A
              git commit --allow-empty \
                -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}"
              git push origin gh-pages
            fi'
